services:
    create_resource.command_handler:
        class: App\Application\Resource\Command\CreateResourceCommandHandler
        calls:
            - [addValidator, ['@create_resource.command_validator']]
        tags:
            - { name: command_handler, handles: create_resource }

    delete_resource.command_handler:
        class: App\Application\Resource\Command\DeleteResourceCommandHandler
        tags:
            - { name: command_handler, handles: delete_resource }